#!/usr/bin/env bash
#
# Copyright 2021 Philadelphia authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script builds Philadelphia Performance Test for the release candidate
# and copies it under the name 'candidate.jar'.
#
# Run this script as follows:
#
#   ./scripts/build-candidate
#

set -e

filename="candidate.jar"

if [[ -e "$filename" ]]; then
    echo "error: $filename: File exists" >&2
    exit 1
fi

git checkout -q master

echo "Building '$filename'..."

mvn -q clean package -am -pl tests/perf-test
cp tests/perf-test/philadelphia-perf-test.jar "$filename"

git checkout -q -
