#!/usr/bin/env bash
#
# Copyright 2020 Philadelphia authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script generates FIX protocol versions from FIX Orchestra. For more
# information on FIX Orchestra, see:
#
#   https://www.fixtrading.org/standards/fix-orchestra/
#
# This script uses Philadelphia Code Generator and therefore requires Python
# 3.7 or newer.
#
# As this repository already contains the generated FIX protocol versions, you
# only need to run this script if FIX Latest or FIXT 1.1 updates or you change
# Philadelphia Code Generator.
#

set -e

generate() {
    local command=$1
    local config_file=$2
    local input_path=$3
    local output_path=$4

    cat scripts/license-orchestra.java > "$output_path"

    if [[ $input_path != /* ]]; then
        input_path="../../$input_path"
    fi

    (cd applications/generate; \
            python -m philadelphia.generate "$command" "../../$config_file" "$input_path" \
                    >> "../../$output_path")
}

generate_version() {
    local input_file=$1
    local output_prefix=$2

    local output_module=${output_prefix,,}

    local config_file="scripts/config-$output_module.ini"
    local output_dir="libraries/$output_module/src/main/java/com/paritytrading/philadelphia/$output_module"

    generate enumerations "$config_file" "$input_file" "$output_dir/${output_prefix}Enumerations.java"
    generate msg-types "$config_file" "$input_file" "$output_dir/${output_prefix}MsgTypes.java"
    generate tags "$config_file" "$input_file" "$output_dir/${output_prefix}Tags.java"
}

if [[ $# != 1 ]]; then
    echo "Usage: ${0##*/} <input-directory>" >&2
    exit 2
fi

input_dir=$1

generate_version "$input_dir/OrchestraFIXLatest.xml" "FIXLatest"
generate_version "$input_dir/FIXTSession.xml" "FIXT11"
