#!/usr/bin/env bash
#
# Copyright 2015 Philadelphia authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script generates the FIX protocol versions from the FIX Repository. For
# more information on the FIX Repository, see:
#
#   https://www.fixtrading.org/standards/fix-repository/
#
# This script uses Philadelphia Code Generator and therefore requires Python
# 3.5 or newer.
#

set -e

generate() {
    local command=$1
    local input_path=$2
    local output_path=$3

    cat scripts/license.java > "$output_path"

    (cd applications/generate; \
            python -m philadelphia.generate "$command" "$input_path" >> "../../$output_path")
}

generate_version() {
    local input_dir=$1
    local input_version=$2

    local output_prefix=${input_version//./}
    local output_module=${output_prefix,,}

    local input_path="$input_dir/$input_version/Base"
    local output_dir="libraries/$output_module/src/main/java/com/paritytrading/philadelphia/$output_module"

    generate enumerations "$input_path" "$output_dir/${output_prefix}Enumerations.java"
    generate msg-types "$input_path" "$output_dir/${output_prefix}MsgTypes.java"
    generate tags "$input_path" "$output_dir/${output_prefix}Tags.java"
}

if [[ $# != 1 ]]; then
    echo "Usage: ${0##*/} <input-directory>" >&2
    exit 2
fi

input_dir=$1

generate_version "$input_dir" "FIX.4.2"
generate_version "$input_dir" "FIX.4.3"
generate_version "$input_dir" "FIX.4.4"
generate_version "$input_dir" "FIX.5.0"
generate_version "$input_dir" "FIX.5.0SP1"
generate_version "$input_dir" "FIX.5.0SP2"
generate_version "$input_dir" "FIXT.1.1"
