#!/usr/bin/env bash
#
# Copyright 2020 Philadelphia authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# This script generates FIX Latest from FIX Orchestra. For more information on
# FIX Orchestra, see:
#
#   https://www.fixtrading.org/standards/fix-orchestra/
#
# This script uses Philadelphia Code Generator and therefore requires Python
# 3.5 or newer.
#
# As this repository already contains FIX Latest, you only need to run this
# script if FIX Latest updates or you change Philadelphia Code Generator.
#

set -e

config_file="scripts/fixlatest.ini"
output_dir="libraries/fixlatest/src/main/java/com/paritytrading/philadelphia/fixlatest"
output_prefix="FIXLatest"

generate() {
    local command=$1
    local input_path=$2
    local output_path=$3

    cat scripts/license-fixlatest.java > "$output_path"

    (cd applications/generate; \
            python -m philadelphia.generate "$command" "../../$config_file" "../../$input_path" \
                    >> "../../$output_path")
}

if [[ $# != 1 ]]; then
    echo "Usage: ${0##*/} <input-file>" >&2
    exit 2
fi

input_file=$1

generate enumerations "$input_file" "$output_dir/${output_prefix}Enumerations.java"
generate msg-types "$input_file" "$output_dir/${output_prefix}MsgTypes.java"
generate tags "$input_file" "$output_dir/${output_prefix}Tags.java"
